redouane59/twittered

- src/main/java/com/socialmediaraiser/twitter/helpers/RequestHelper.java
- src/main/resources/cache-config.json
To avoid having cache value in the code.
A json file is now available
> feat: cache config file

- src/main/java/com/socialmediaraiser/twitter/ITwitterClient.java
- src/main/java/com/socialmediaraiser/twitter/TwitterClient.java
- src/main/java/com/socialmediaraiser/twitter/dto/others/BearerTokenDTO.java
- src/main/java/com/socialmediaraiser/twitter/dto/tweet/TweetSearchV2DTO.java
- src/main/java/com/socialmediaraiser/twitter/helpers/AbstractRequestHelper.java
- src/main/java/com/socialmediaraiser/twitter/helpers/ConverterHelper.java
- src/main/java/com/socialmediaraiser/twitter/helpers/RequestHelper.java
- src/main/java/com/socialmediaraiser/twitter/helpers/RequestHelperV2.java
- src/main/java/com/socialmediaraiser/twitter/helpers/URLHelper.java
- src/main/resources/tests/bearer_token_example.json
- src/main/resources/tests/tweet_list_v2_search_lab_example.json
- src/test/java/com/socialmediaraiser/twitter/nrt/TwitterClientTest.java
- src/test/java/com/socialmediaraiser/twitter/unit/UrlHelperTest.java
See https://developer.twitter.com/en/docs/labs/recent-search/api-reference/get-recent-search-v1
Need to modify the authentication type : 
- Implement a request to get a bearer token
- Edit the existing ones to use bearer token
> feat: labs 7 days search

- src/main/java/com/socialmediaraiser/twitter/ITwitterClient.java
- src/main/java/com/socialmediaraiser/twitter/TwitterClient.java
- src/main/java/com/socialmediaraiser/twitter/dto/tweet/TweetDTOv2.java
- src/main/java/com/socialmediaraiser/twitter/dto/user/IUser.java
- src/main/java/com/socialmediaraiser/twitter/dto/user/PublicMetrics.java
- src/main/java/com/socialmediaraiser/twitter/dto/user/UserDTOv2.java
- src/main/java/com/socialmediaraiser/twitter/dto/user/UserPublicMetrics.java
- src/main/java/com/socialmediaraiser/twitter/helpers/URLHelper.java
- src/main/resources/tests/tweet_example_v2.json
- src/main/resources/tests/user_example_v2.json
- src/test/java/com/socialmediaraiser/twitter/nrt/TwitterClientTest.java
- src/test/java/com/socialmediaraiser/twitter/unit/TweetDeserializerTestV2.java
- src/test/java/com/socialmediaraiser/twitter/unit/UrlHelperTest.java
- src/test/java/com/socialmediaraiser/twitter/unit/UserDeserializerTestV2.java
See : [https://twittercommunity.com/t/releasing-a-new-version-of-labs-endpoints/134219](https://twittercommunity.com/t/releasing-a-new-version-of-labs-endpoints/134219)
> feat: implementing labs v2 

- src/main/java/com/socialmediaraiser/twitter/dto/tweet/ContextAnnotation.java
- src/main/java/com/socialmediaraiser/twitter/dto/tweet/ITweet.java
- src/main/java/com/socialmediaraiser/twitter/dto/tweet/TweetDTOv1.java
- src/main/java/com/socialmediaraiser/twitter/dto/tweet/TweetDTOv2.java
- src/main/java/com/socialmediaraiser/twitter/helpers/URLHelper.java
- src/main/resources/cache-config.json
- src/main/resources/tests/tweet_example_v2.json
- src/test/java/com/socialmediaraiser/twitter/unit/TweetDeserializerV2Test.java
- src/test/java/com/socialmediaraiser/twitter/unit/UrlHelperTest.java
Related to https://github.com/redouane59/twitter-client/issues/12
> feat: adding context_annotations to tweets

- src/main/java/com/socialmediaraiser/twitter/TwitterClient.java
Related to https://github.com/redouane59/twitter-client/issues/12
> feat: add context annotations to recent search labs

- src/main/java/com/socialmediaraiser/twitter/ITwitterClient.java
- src/main/java/com/socialmediaraiser/twitter/TwitterClient.java
- src/main/java/com/socialmediaraiser/twitter/helpers/URLHelper.java
- src/test/java/com/socialmediaraiser/twitter/nrt/TwitterClientTest.java
[Twitter Documentation](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-favorites-list)
> feat: get favourites v1

- src/main/java/com/socialmediaraiser/twitter/ITwitterClient.java
- src/main/java/com/socialmediaraiser/twitter/TwitterClient.java
- src/main/java/com/socialmediaraiser/twitter/dto/tweet/TweetDTOv2.java
- src/test/java/com/socialmediaraiser/twitter/nrt/TwitterClientTest.java
Feature to be able to retrieve the initial tweet of a conversation from a tweet
> feat: get_initial_tweet

- src/main/java/com/socialmediaraiser/twitter/ITwitterClient.java
- src/main/java/com/socialmediaraiser/twitter/TwitterClient.java
- src/main/java/com/socialmediaraiser/twitter/dto/tweet/ITweet.java
- src/main/java/com/socialmediaraiser/twitter/dto/tweet/TweetDTOv1.java
- src/main/java/com/socialmediaraiser/twitter/dto/tweet/TweetDTOv2.java
- src/main/java/com/socialmediaraiser/twitter/dto/tweet/TweetType.java
- src/test/java/com/socialmediaraiser/twitter/nrt/TwitterClientTest.java
- To get the type of a tweets : `replied_to`, `quoted`, `retweet` (Labs V2)
- Adding a parameter into `getInitialTweet` to exclude quoted tweets
> feat: tweet type

- src/main/java/com/socialmediaraiser/twitter/dto/tweet/ITweet.java
- src/main/java/com/socialmediaraiser/twitter/dto/tweet/TweetDTOv1.java
- src/main/java/com/socialmediaraiser/twitter/dto/tweet/TweetDTOv2.java
- src/main/java/com/socialmediaraiser/twitter/dto/tweet/TweetType.java
- src/test/java/com/socialmediaraiser/twitter/nrt/TwitterClientTest.java
- Including tweet type as argument
> feat: improve get in reply status id with types

- src/main/java/com/github/redouane59/twitter/helpers/AbstractRequestHelper.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelper.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelperV2.java
In order to use response cache easily in the same way than RequestHelperV1, I will use okHttpClient
> feat: remove java net http client

- README.md
- pom.xml
- src/main/java/com/github/redouane59/twitter/ITwitterClient.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/ITweet.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetDTOv1.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetDTOv2.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelperV2.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/main/resources/tests/tweet_example_v2.json
- src/test/java/com/github/redouane59/twitter/nrt/TwitterClientTest.java
- src/test/java/com/github/redouane59/twitter/unit/TweetDeserializerV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Replacing labs V2 endpoints by official V2 endpoints
> feat: v2 migration

- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/user/UserDTOListv2.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/TwitterClientTest.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
https://api.twitter.com/2/users/
> feat: migration v2 of get users endpoints

- src/main/java/com/github/redouane59/twitter/ITwitterClient.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetDTOListv2.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetDTOv2.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/TwitterClientTest.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Adding https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets
> feat: add get tweets endpoints v2

- README.md
- pom.xml
- src/main/java/com/github/redouane59/twitter/helpers/AbstractRequestHelper.java
Solving https://github.com/redouane59/twitter-client/issues/32
> feat: use program arguments for credentials 

- src/main/java/com/github/redouane59/twitter/ITwitterClient.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelper.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelperV2.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/TwitterClientTest.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
- In order to be able to use bearer token everywhere.
> feat: Migration to RequestHelperV2

- pom.xml
- src/main/java/com/github/redouane59/twitter/ITwitterClient.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelper.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/TwitterClientTest.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Solving https://github.com/redouane59/twitter-client/issues/37
> feat: post tweet V.1.

- src/main/java/com/github/redouane59/twitter/ITwitterClient.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/HiddenResponseDTO.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelper.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelperV2.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/TwitterClientTest.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Implementing https://developer.twitter.com/en/docs/labs/hide-replies/api-reference/put-hidden
> feat: hide reply methods

- README.md
- src/main/java/com/github/redouane59/twitter/ITwitterClientArchive.java
- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientArchiveTest.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
Partially solving https://github.com/redouane59/twitter-client/issues/44
> feat: split client interfaces between V1, V2 and Archive 

- README.md
- pom.xml
- Change repository name from `twitter-client` to `twittered`
> feat: rename repository

- .gitignore
- pom.xml
- src/main/java/com/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetSearchResponse.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetSearchResponseV1.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetSearchResponseV2.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelperV2.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Sovling https://github.com/redouane59/twittered/issues/46
> feat: search_with_next_token

- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
See https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-destroy-id
> feat: delete tweet v1

- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Implementing https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-retweet-id
> feat: retweet tweet v1

- src/main/java/com/github/redouane59/twitter/helpers/RequestHelperV2.java
Fixing the exceptions received when calling the stream endpoints
> fix: stream exceptions

- README.md
- pom.xml
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelperV2.java
Trying to fix https://github.com/redouane59/twittered/issues/45
> fix: connection never closed

- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetType.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetV1.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetV2.java
Fixing https://github.com/redouane59/twittered/issues/63
> fix: getTweetType returning null when no data

- README.md
- pom.xml
- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelper.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
See https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-mentions_timeline
> feat: mentions timeline v1

- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-update
> feat: post reply tweet  v1

- pom.xml
- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/others/RequestToken.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
Adding callback parameter.
See : 
https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens
https://developer.twitter.com/en/docs/apps/callback-urls
> fix: get oauth1 token

- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Solving https://github.com/redouane59/twittered/issues/81
> feat: add sampled stream extensions

- pom.xml
> feat: update_pom_version

- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/Tweet.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetV2.java
- src/main/java/com/github/redouane59/twitter/dto/user/User.java
- src/main/java/com/github/redouane59/twitter/dto/user/UserV1.java
- src/main/java/com/github/redouane59/twitter/dto/user/UserV2.java
- src/test/java/com/github/redouane59/twitter/unit/UserDeserializerV1Test.java
- src/test/java/com/github/redouane59/twitter/unit/UserDeserializerV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UserV1Test.java
- Fixing https://github.com/redouane59/twittered/issues/87
- Fixing equals between UserV1 and UserV2 objects
- Cleaning code
> Fix: missing name attribute in DTO and cleaning code

- README.md
- pom.xml
> feat: update_version

- src/main/java/com/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Related to academic plan. See : https://developer.twitter.com/en/solutions/academic-research/resources
> feat: full archive search

- README.md
Just a little update in the readme.
Maybe to avoid having to update it every time you could just put a placeholder like `<version>VERSION</version>` and have a badge pointing to the latest version (eg: ![Maven Central](https://img.shields.io/maven-central/v/com.github.redouane59.twitter/twittered) => `![Maven Central](https://img.shields.io/maven-central/v/com.github.redouane59.twitter/twittered)`).
> Update latest version in readme

- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
> feat: user_mentions_v2

- src/main/java/com/github/redouane59/twitter/dto/tweet/ReplySettings.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/Tweet.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetV1.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetV2.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/unit/TweetDeserializerV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
- src/test/resources/tests/tweet_example_v2.json
> feat: add reply settings field to Tweet Object V2

- pom.xml
- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/MediaCategory.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/UploadMediaResponse.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelper.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Implementing https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-upload-init
> feat: upload media endpoint

- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
In order to allow answers to all the users mentioned in a tweet
> feat: auto_populate_post_tweet

- src/main/java/com/github/redouane59/twitter/helpers/AbstractRequestHelper.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelper.java
Following @PhantomYdn feedback !
> fix: OkHttpClient Singleton

- pom.xml
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
User object was missing calling stream endpoint
> feat: add stream user expansions

- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
> fix: oauth_access_token

- .gitignore
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
- test-twitter-credentials.json
> feat: tweet_mode_extended_v1_favourites

- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/user/FollowBody.java
- src/main/java/com/github/redouane59/twitter/dto/user/FollowResponse.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Solving https://github.com/redouane59/twittered/issues/131
> feat: implementing follow & unfollow endpoints V2

- pom.xml
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetV2.java
- In order to be able to access to it from outside.
> feat: replace private static classes of TweetV2 by public static classes

- .github/workflows/build.yml
- pom.xml
- src/main/java/com/github/redouane59/twitter/dto/user/UserV2.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
Setting up sonar and fixing some bugs
> feat: sonar set up

- src/main/java/com/github/redouane59/twitter/dto/tweet/Attachments.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/Geo.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/Tweet.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetV1.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetV2.java
- src/test/java/com/github/redouane59/twitter/unit/TweetDeserializerV2Test.java
- src/test/resources/tests/tweet_example_v2.json
fixing https://github.com/redouane59/twittered/issues/149
> feat: add missing tweet fields

- src/main/java/com/github/redouane59/twitter/dto/collections/TimeLineOrder.java
Related to https://github.com/redouane59/twittered/pull/114
> fix: collections timeline order

- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
fixing  https://github.com/redouane59/twittered/issues/154
> feat: improving post tweet documentation

- pom.xml
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/AbstractRequestHelper.java
- src/main/java/com/github/redouane59/twitter/helpers/RequestHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/RequestHelperTest.java
> fix: oauth1 endpoints to access protected content

- pom.xml
- src/main/java/com/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/others/BlockResponse.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
See: https://developer.twitter.com/en/docs/twitter-api/users/blocks/api-reference
> feat: block & unblock endpoints v2

- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
> feat: add max_results property to followers/following endpoints

- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/LikeResponse.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
> feat: implement likes endpoints v2

- src/main/java/com/github/redouane59/twitter/TwitterClient.java
Fixing https://github.com/redouane59/twittered/issues/177
> fix: full archive search

- src/main/java/com/github/redouane59/twitter/dto/user/User.java
- src/main/java/com/github/redouane59/twitter/dto/user/UserV1.java
- src/main/java/com/github/redouane59/twitter/dto/user/UserV2.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
- src/test/java/com/github/redouane59/twitter/unit/UserDeserializerV2Test.java
- src/test/resources/tests/user_example_v2.json
Sovling https://github.com/redouane59/twittered/issues/180
> feat: improve userV2 object

- src/main/java/com/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Implemeting liking users endpoint.
See Twitter Announce [here](https://twittercommunity.com/t/announcing-twitter-api-v2-likes-lookup-and-blocks-lookup/154353)
> feat: liking users

- pom.xml
- src/main/java/com/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/tweet/TweetListV2.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Implementing [liked endpoint](https://developer.twitter.com/en/docs/twitter-api/tweets/likes/api-reference/get-users-id-liked_tweets)
> feat: liked tweets

- pom.xml
- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/AbstractRequestHelper.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Solving https://github.com/redouane59/twittered/issues/194
> feat: add attachment url in post tweet v1 endpoint

- src/main/java/com/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2AuthenticatedTest.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
Solving https://github.com/redouane59/twittered/issues/195
> feat: implement get blocked users endpoint v2

- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
Solving https://github.com/redouane59/twittered/issues/188
> fix: get mentions or timelines with dates

- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
Fixing https://github.com/redouane59/twittered/issues/188
> fix: get mentions endpoint with dates

- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/dm/DmListAnswer.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/unit/DMDeserializarTest.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
- src/test/resources/tests/dm_list_example.json
See https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/sending-and-receiving/api-reference/list-events
> feat: implement get dm list v1 endpoint

- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/dm/DirectMessage.java
- src/main/java/com/github/redouane59/twitter/dto/dm/DmAnswer.java
- src/main/java/com/github/redouane59/twitter/dto/dm/DmListAnswer.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
See https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/sending-and-receiving/api-reference/get-event
> feat: get dm v1

- pom.xml
- src/main/java/com/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/com/github/redouane59/twitter/TwitterClient.java
- src/main/java/com/github/redouane59/twitter/dto/dm/DirectMessage.java
- src/main/java/com/github/redouane59/twitter/dto/dm/DmEvent.java
- src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/com/github/redouane59/twitter/unit/DMDeserializarTest.java
- src/test/java/com/github/redouane59/twitter/unit/UrlHelperTest.java
See : https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/sending-and-receiving/api-reference/new-event
> feat: post DM

- LICENSE
- pom.xml
- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/dto/endpoints/AdditionalParameters.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/TweetList.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- Add default value for `MAX_RESULT`
- Set recursive calls as default behavior
- Improve javadoc
> feat: improve method additional parameters

- pom.xml
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/dto/getrelationship/UserListV1.java
- src/main/java/io/github/redouane59/twitter/dto/user/UserList.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
Solving https://github.com/redouane59/twittered/issues/186
> feat: update getFollowers and getFollowing recursive calls management

- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/helpers/RequestHelperV2.java
- src/main/java/io/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/io/github/redouane59/twitter/unit/UrlHelperTest.java
See : https://twittercommunity.com/t/new-reliability-and-recovery-functionality-available-for-twitter-api-v2-streaming-endpoints/156244
> feat: implement new reliability and recovery v2 for streaming endpoints

- pom.xml
- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/dto/endpoints/AdditionalParameters.java
- src/main/java/io/github/redouane59/twitter/dto/user/UserActionResponse.java
- src/main/java/io/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2AuthenticatedTest.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/io/github/redouane59/twitter/unit/UrlHelperTest.java
Solving https://github.com/redouane59/twittered/issues/164
> feat: implement mute endpoints v2

- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/helpers/AbstractRequestHelper.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
Solving https://github.com/redouane59/twittered/issues/186
```
TwitterClient twitterClient = new TwitterClient(...);
twitterClient.setAutomaticRetry(false);
// next calls will raise exceptions in case of rate limit exceeded 
```
> feat: allow raising exception instead of sleeping when api limit are reached

- src/main/java/io/github/redouane59/twitter/helpers/AbstractRequestHelper.java
- src/main/java/io/github/redouane59/twitter/helpers/ConverterHelper.java
Fixing https://github.com/redouane59/twittered/issues/238
> fix: sleep log

- src/main/java/io/github/redouane59/twitter/dto/tweet/TweetV2.java
- src/main/java/io/github/redouane59/twitter/dto/user/UserV2.java
- src/test/java/io/github/redouane59/twitter/unit/UserDeserializerV2Test.java
- src/test/resources/tests/user_example_v2.json
Fixing https://github.com/redouane59/twittered/issues/237
Adding `@JsonIgnore` properties to method throwing exception to allow serialization in `UserV2` and `TweetV2` class.
> fix: User & Tweet serialization

- src/main/java/io/github/redouane59/twitter/dto/tweet/TweetV2.java
- src/main/java/io/github/redouane59/twitter/dto/user/UserV2.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
Test with user get from api : 
```
@Test
public void getAndSerializeUser() throws IOException {
String userName = "RedouaneBali";
User   result   = twitterClient.getUserFromUserName(userName);
assertNotNull(TwitterClient.OBJECT_MAPPER.writeValueAsString(result));
TwitterClient.OBJECT_MAPPER.writeValue(new File("../test_serialization.json"), result);
}
```
> fix: serialization 2

- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
Fixing : https://github.com/redouane59/twittered/issues/251
> fix: recursive call for oauth2 endpoints

- src/main/java/io/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/io/github/redouane59/twitter/unit/UrlHelperTest.java
Solving https://github.com/redouane59/twittered/issues/243
> feat: add getFollowing v1

- src/main/java/io/github/redouane59/twitter/TwitterClient.java
> fix: searchAllTweents max result management

- README.md
Fixes for the readme links, so they don't give 404s
> change links to point to dev branch

- pom.xml
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- Updates several 3rd party dependencies
- Unifies plugin dependency configuration
> Updates several 3rd party dependencies

- LICENSE
- Switches codebase to ASL 2.0 license
> Switches codebase to ASL 2.0 license

- .idea/codeStyles/codeStyleConfig.xml
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/dto/rules/FilteredStreamRulePredicate.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/TweetV1.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/TweetV2.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/entities/BaseEntity.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/entities/Entities.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/entities/HashtagEntity.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/entities/MediaEntity.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/entities/SymbolEntity.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/entities/TextBaseEntity.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/entities/UrlEntity.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/entities/UserMentionEntity.java
- src/test/java/io/github/redouane59/twitter/dto/rules/FilteredStreamRulePredicateTest.java
- src/test/java/io/github/redouane59/twitter/unit/TweetDeserializerV1Test.java
- src/test/java/io/github/redouane59/twitter/unit/TweetDeserializerV2Test.java
- src/test/resources/tests/relationship_example.json
- src/test/resources/tests/tweet_example_v1.json
- src/test/resources/tests/tweet_example_v2.json
See : https://twittercommunity.com/t/media-alt-text-field-now-available-in-twitter-api-v2/157939
- applying google style to all the project.
> feat: adding alt text

- src/main/java/io/github/redouane59/twitter/dto/space/Space.java
- src/test/java/io/github/redouane59/twitter/unit/SpaceDeserializerTest.java
- src/test/resources/tests/space_example.json
See : https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/space
> feat: create Space object

- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/dto/space/Space.java
- src/main/java/io/github/redouane59/twitter/dto/space/SpaceList.java
- src/main/java/io/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/io/github/redouane59/twitter/unit/UrlHelperTest.java
See https://developer.twitter.com/en/docs/twitter-api/spaces/lookup/api-reference/get-spaces-id
> feat: implement space lookup endpoints

- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/dto/user/User.java
- src/main/java/io/github/redouane59/twitter/dto/user/UserV1.java
- src/main/java/io/github/redouane59/twitter/dto/user/UserV2.java
Solving https://github.com/redouane59/twittered/issues/293
> feat: add profile image url in User interface

- src/main/java/io/github/redouane59/twitter/dto/user/UserV2.java
Fixing https://github.com/redouane59/twittered/issues/295
> fix: get pinned tweet NPE

- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
Fixing https://github.com/redouane59/twittered/issues/293
> feat: add user fields to search endpoints

- src/main/java/io/github/redouane59/twitter/helpers/ConverterHelper.java
- src/test/java/io/github/redouane59/twitter/unit/ConverterHelperTest.java
Solving https://github.com/redouane59/twittered/issues/283
> feat: adding tweet methods to converter

- pom.xml
- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2AuthenticatedTest.java
See https://developer.twitter.com/en/docs/twitter-api/users/mutes/api-reference/get-users-muting
> feat: implement get muted users endpoint

- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/dto/list/TwitterList.java
- src/main/java/io/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2AuthenticatedTest.java
See https://developer.twitter.com/en/docs/twitter-api/lists/manage-lists/api-reference/post-lists
> feat: create and delete lists

- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/dto/list/TwitterListMember.java
- src/main/java/io/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2AuthenticatedTest.java
See: https://developer.twitter.com/en/docs/twitter-api/lists/manage-lists/api-reference/post-lists-id-members
> feat: manage list members

- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/dto/list/TwitterList.java
- src/main/java/io/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2AuthenticatedTest.java
See https://developer.twitter.com/en/docs/twitter-api/lists/manage-lists/api-reference/post-users-id-pinned-lists
> feat: manage pin list v2

- pom.xml
- src/main/java/io/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/TweetParameters.java
- src/main/java/io/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV1Test.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2AuthenticatedTest.java
- src/test/java/io/github/redouane59/twitter/unit/UrlHelperTest.java
See https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/migrate
> feat: implement Post & Delete Tweet V2

- pom.xml
- src/main/java/io/github/redouane59/twitter/ITwitterClientV1.java
- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/dto/list/TwitterList.java
- src/main/java/io/github/redouane59/twitter/dto/list/TwitterListList.java
- src/main/java/io/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- src/test/java/io/github/redouane59/twitter/unit/TwitterListDeserializerTest.java
- src/test/java/io/github/redouane59/twitter/unit/TwitterListListDeserializerTest.java
- src/test/resources/tests/twitter_list_example_v2.json
- src/test/resources/tests/twitter_list_list_example_v2.json
See https://developer.twitter.com/en/docs/twitter-api/lists/list-lookup/api-reference/get-lists-id#Optional 
Replacing : https://github.com/redouane59/twittered/pull/322 + adding new endpoint to get lists by id
> feat: implement get list endpoints v2

- src/main/java/io/github/redouane59/twitter/dto/tweet/Tweet.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/TweetV1.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/TweetV2.java
- src/test/java/io/github/redouane59/twitter/unit/StreamTweetDeserializerTest.java
fixing https://github.com/redouane59/twittered/issues/330
> feat: add matching rules to Tweet

- pom.xml
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
Solving https://github.com/redouane59/twittered/issues/327
> feat: add error log when adding existing rule

- src/main/java/io/github/redouane59/twitter/dto/rules/FilteredStreamRulePredicate.java
- src/test/java/io/github/redouane59/twitter/dto/rules/FilteredStreamRulePredicateTest.java
> Resolves #344 "Wrong FilteredStreamRulePredicate#and(FilteredStreamRulePredicate) implementation"

- .gitignore
- pom.xml
- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2Test.java
- test-twitter-credentials.json
See https://twittercommunity.com/t/updates-to-retweets-lookup-and-likes-lookup-endpoints/165327
> feat: pagination for likes and retweets endpoints

- pom.xml
See comments in https://github.com/redouane59/twittered/pull/369
> fix pom sonar plugin

- src/main/java/io/github/redouane59/twitter/helpers/AbstractRequestHelper.java
> Fix for issue #379

- src/main/java/io/github/redouane59/twitter/helpers/AbstractRequestHelper.java
See [To solve the: Change retry header #409 #410](https://github.com/redouane59/twittered/pull/410)
> fix; wrong retry header

- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2AuthenticatedTest.java
See https://developer.twitter.com/en/docs/twitter-api/direct-messages/lookup/api-reference/get-dm_conversations-dm_conversation_id-dm_events#tab0
> feat: dm lookup endpoint v2

- src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
- src/main/java/io/github/redouane59/twitter/TwitterClient.java
- src/main/java/io/github/redouane59/twitter/dto/dm/DmParameters.java
- src/main/java/io/github/redouane59/twitter/dto/dm/PostDmResponse.java
- src/main/java/io/github/redouane59/twitter/helpers/URLHelper.java
- src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2AuthenticatedTest.java
- src/test/java/io/github/redouane59/twitter/unit/UrlHelperTest.java
See https://developer.twitter.com/en/docs/twitter-api/direct-messages/manage/api-reference/
> feat: implement post DM V2 endpoints

- src/main/java/io/github/redouane59/twitter/dto/dm/DmParameters.java
- src/main/java/io/github/redouane59/twitter/dto/endpoints/AdditionalParameters.java
- src/main/java/io/github/redouane59/twitter/dto/list/TwitterListMember.java
- src/main/java/io/github/redouane59/twitter/dto/space/Space.java
- src/main/java/io/github/redouane59/twitter/dto/space/SpaceList.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/Attachments.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/Geo.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/LikeResponse.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/RetweetResponse.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/TweetCountsList.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/TweetList.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/TweetParameters.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/TweetV1.java
- src/main/java/io/github/redouane59/twitter/dto/tweet/TweetV2.java
- src/main/java/io/github/redouane59/twitter/dto/user/UserActionResponse.java
- src/main/java/io/github/redouane59/twitter/dto/user/UserList.java
- src/main/java/io/github/redouane59/twitter/dto/user/UserV1.java
- src/main/java/io/github/redouane59/twitter/dto/user/UserV2.java
- src/main/java/io/github/redouane59/twitter/signature/TwitterCredentials.java
I was getting errors like this when deserializing `TweetV2` with Jackson.  Adding `@Jacksonized` should fix them.
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.UnsupportedOperationException) (through reference chain: io.github.redouane59.twitter.dto.tweet.TweetV2["media"]->java.util.Collections$EmptyList[0])
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392)
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:363)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:371)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:272)
at …
```
> Added @Jacksonized to all @Builder classes
